### ISSUE TITLE
Provide the list of all possible arguments 

### ISSUE THREAD

**Issue by thyamu** [ELIFE-ASU/ecg#13]
https://github.com/ELIFE-ASU/ecg/blob/a07d0c3dc75bfb7a5fb22ba7b001e9f59e913852/ecg/jgi.py#L10

Write the list of all possible arguments at the beginning of description for the script as it is done under the function "scape_domain". 

For example, for domain, 

 ## Alpha
            'Eukaryota'
            'Bacteria' (wait 45 seconds)
            'Archaea'
            'Plasmids' UNTESTED
            'Viruses' UNTESTED
            'GFragment' (gene fragments) UNTESTED
            ## Alpha2
            '*Microbiome' (metagenome)
            'cell' (metagenome- cell enrichment) UNTESTED
            'sps' (metagenome- single particle sort) UNTESTED
            'Metatranscriptome' UNTESTED

**Comment by hbsmith** [comment]
This is included with the latest commits.
