### ISSUE TITLE
Documentation about post-processing of KEGG and JGI data to construct graphs

### ISSUE THREAD

**Issue by thyamu** [ELIFE-ASU/ecg#17]
To convert EC lists to graphs
 1. rxn_edges.json
 2. rxn_detalied_json_dir
 3. genome_rxn_list

**Comment by hbsmith** [comment]
I'm working on an update to address this. Right now, we don't actually generate or use networkx graphs or gmls as part of the pipeline for network expansion, but it's useful to have anyways.

**Comment by hbsmith** [comment]
This is closed in the latest batch of commits, with the update to the `README.md` in 637169a4e93f81ec5f1b22ea96a278715a350c35.
