### ISSUE TITLE
add to README.md: simplified stepwise installation instructions

### ISSUE THREAD

**Issue by camerianm** [ELIFE-ASU/ecg#27]
Brand-new users might not know that dependencies aren't automatically installed, and might not feel confident choosing from a list of local installation options... all of which assume both (1) a preferred and pre-existing directory structure, and (2) successful execution of unstated installation steps. It could be smart to add a "quick setup" section for novice users near the top of the README. e.g....

Open your [terminal](https://support.apple.com/guide/terminal/open-or-quit-terminal-apd5265185d-f365-44cb-8b09-71a064a42125/mac) or other Unix/[Linux command-line interface](https://learn.microsoft.com/en-us/windows/wsl/install). Use it to navigate to your desktop, documents, or other folder in which you tend to store projects (e.g. ```cd Desktop/```). Then, copy+paste into the terminal each of the following lines:
```
mkdir ecgHub
pip install docopt; pip install tqdm; pip install biopython; pip install selenium; pip install beautifulsoup4; pip install networkx
cd ecgHub
git clone https://github.com/ELIFE-ASU/ecg
cd ecg
pip install -e
mkdir mydata
```
The command ```import ecg``` should now work for any Python scripts or Jupyter Notebooks created and stored in the **top-level** ```ecg``` directory (i.e. ```ecgHub/ecg```). Files not used by ```ecg``` or generated with ```ecg```, but which are relevant or occasionally needed in **scripts** which import ```ecg```, can then be stored in the ```ecgHub``` folder. (manuscripts, notes, templates, auxiliary csvs, etc.)

**Comment by colemathis** [comment]
This was closed by PR #28
